"""Strategy code generation — produce a self-contained, executable Python script.

Given a 13-gene chromosome, emit a standalone Python source file that re-runs
the backtest deterministically.  Also supports YAML round-tripping so a
strategy can be persisted and reloaded by gene name.

Usage::

    from src.export.codegen import generate_backtest_code, export_strategy_yaml, load_strategy_yaml

    code = generate_backtest_code(individual)
    with open("strategy.py", "w") as f:
        f.write(code)

    export_strategy_yaml(individual, "results/strategy.yaml")
    ind2 = load_strategy_yaml("results/strategy.yaml")
"""

from __future__ import annotations

import os
import textwrap
from pathlib import Path
from typing import Union

import yaml

from src.ga.chromosome import GENE_NAMES, N_GENES


def generate_backtest_code(
    individual: list,
    warmup_bars: int = 252,
    train_fraction: float = 0.40,
) -> str:
    """Generate a self-contained Python script that re-runs the backtest.

    The generated script imports from the ``src`` package, loads SPY data,
    builds the indicator cache, generates signals, and runs the backtest
    engine — reproducing exactly the same result as the GA evaluation.

    Args:
        individual:     13-gene chromosome list.
        warmup_bars:    Warmup bars used during optimisation (default 252).
        train_fraction: Train/test split fraction used during optimisation (default 0.40).

    Returns:
        Python source code as a string.

    Raises:
        ValueError: If individual does not have exactly 13 genes.
    """
    if len(individual) != N_GENES:
        raise ValueError(f"Individual must have {N_GENES} genes, got {len(individual)}")

    genes_repr = repr(list(individual))
    # Build gene_comments with uniform 4-space indent so textwrap.dedent works correctly
    gene_comments_raw = "\n".join(
        f"# [{i:2d}] {GENE_NAMES[i]:<22} = {individual[i]}"
        for i in range(N_GENES)
    )
    gene_comments = textwrap.indent(gene_comments_raw, "        ")

    return textwrap.dedent(f"""\
        \"\"\"Auto-generated strategy backtest script.

        Generated by ga-trading-sys codegen.
        Re-run with: python strategy.py

        Chromosome:
{gene_comments}
        \"\"\"

        from __future__ import annotations

        import sys
        from pathlib import Path

        # Ensure src is importable when running standalone
        sys.path.insert(0, str(Path(__file__).resolve().parent))

        import numpy as np

        from src.backtesting.numba_engine import NumbaBacktestEngine, warmup_jit
        from src.ga.chromosome import IDX_STOP_LOSS_PCT, IDX_TAKE_PROFIT_PCT, IDX_POSITION_SIZE_MULT
        from src.indicators.calculator import build_indicator_cache
        from src.indicators.signal_generator import generate_signals_weighted_sum, get_entry_signals

        # ---------------------------------------------------------------------------
        # Strategy genes
        # ---------------------------------------------------------------------------

        INDIVIDUAL = {genes_repr}

        # ---------------------------------------------------------------------------
        # Configuration
        # ---------------------------------------------------------------------------

        TICKER          = "SPY"
        START_DATE      = "2010-01-01"
        END_DATE        = "2024-12-31"
        WARMUP_BARS     = {warmup_bars}
        NORM_WINDOW     = 252
        TRAIN_FRACTION  = {train_fraction}

        # ---------------------------------------------------------------------------
        # Main
        # ---------------------------------------------------------------------------


        def main() -> None:
            from src.data.loader import load_market_data

            print(f"Loading {{TICKER}} data …")
            df = load_market_data(TICKER, START_DATE, END_DATE)

            print(f"Loaded {{len(df)}} bars; warming up Numba …")
            warmup_jit()
            engine = NumbaBacktestEngine()

            cache = build_indicator_cache(df, normalization_window=NORM_WINDOW)
            sliced_cache = {{k: v[WARMUP_BARS:] for k, v in cache.items()}}
            prices = df["close"].values[WARMUP_BARS:].astype(np.float32)

            n_train = int(len(prices) * TRAIN_FRACTION)
            train_prices  = prices[:n_train]
            test_prices   = prices[n_train:]
            train_cache   = {{k: v[:n_train] for k, v in sliced_cache.items()}}
            test_cache    = {{k: v[n_train:] for k, v in sliced_cache.items()}}

            sl_pct   = float(INDIVIDUAL[IDX_STOP_LOSS_PCT])
            tp_pct   = float(INDIVIDUAL[IDX_TAKE_PROFIT_PCT])
            pos_mult = float(INDIVIDUAL[IDX_POSITION_SIZE_MULT])

            entry_threshold = float(INDIVIDUAL[9])
            train_signals = get_entry_signals(generate_signals_weighted_sum(INDIVIDUAL, train_cache), entry_threshold)
            test_signals  = get_entry_signals(generate_signals_weighted_sum(INDIVIDUAL, test_cache),  entry_threshold)

            train_result = engine.run(train_signals, train_prices, sl_pct, tp_pct, pos_mult)
            test_result  = engine.run(test_signals,  test_prices,  sl_pct, tp_pct, pos_mult)

            print("\\n--- Train ---")
            print(f"  PF={{train_result.profit_factor:.4f}}  trades={{train_result.n_trades}}"
                  f"  PnL=${{train_result.total_pnl:,.0f}}")

            print("\\n--- Test (out-of-sample) ---")
            print(f"  PF={{test_result.profit_factor:.4f}}  trades={{test_result.n_trades}}"
                  f"  PnL=${{test_result.total_pnl:,.0f}}")


        if __name__ == "__main__":
            main()
        """)


def export_strategy_yaml(individual: list, path: Union[str, Path]) -> None:
    """Save an individual as a YAML dict keyed by gene name.

    Args:
        individual: 13-gene chromosome list.
        path:       Destination path (parent dirs created if needed).

    Raises:
        ValueError: If individual length != 13.
    """
    if len(individual) != N_GENES:
        raise ValueError(f"Individual must have {N_GENES} genes, got {len(individual)}")

    path = Path(path)
    os.makedirs(path.parent, exist_ok=True)
    data = {name: float(individual[i]) for i, name in enumerate(GENE_NAMES)}
    with open(path, "w", encoding="utf-8") as fh:
        yaml.dump(data, fh, default_flow_style=False, sort_keys=False)


def load_strategy_yaml(path: Union[str, Path]) -> list:
    """Load an individual from a YAML file produced by :func:`export_strategy_yaml`.

    Args:
        path: Path to the YAML file.

    Returns:
        13-gene list in chromosome order.

    Raises:
        FileNotFoundError: If *path* does not exist.
        KeyError:          If a required gene name is missing from the YAML.
    """
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(f"Strategy YAML not found: {path}")
    with open(path, "r", encoding="utf-8") as fh:
        data = yaml.safe_load(fh) or {}
    return [float(data[name]) for name in GENE_NAMES]
